version: '3'

services: 
  cloud-weather-postgres:
    image: debezium/postgres:13-alpine
    environment:
      - POSTGRES_DATABASE=cloud_weather-precipitation
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/data/db
    

volumes:
  postgres-data:
